name: fb_auth
description: A Web, Mobile Firebase Auth Plugin
version: 1.2.0
author: Rody Davis <rody.davis.jr@gmail.com>
homepage: https://github.com/rodydavis/fb_auth
issue_tracker: https://github.com/rodydavis/plugins/issues
maintainer: Rody Davis (@rodydavis)
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  bloc: ^2.0.0
  firebase: ^6.0.0
  firebase_auth: ^0.14.0+5
  flutter:
    sdk: flutter
  flutter_bloc: ^2.0.0
  http: ^0.12.0+2
  meta: ^1.7.0
  path_provider: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
