name: fb_auth
description: A Web, Mobile Firebase Auth Plugin
version: 1.1.1
author: Rody Davis <rody.davis.jr@gmail.com>
homepage: https://github.com/rodydavis/fb_auth
issue_tracker: https://github.com/rodydavis/fb_auth
maintainer: Rody Davis (@rodydavis)
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase: ^7.2.1
  firebase_auth: ^0.15.5+2
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  http: ^0.12.0+4
  path_provider: ^1.6.5
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
